set_property IOSTANDARD LVCMOS33 [get_ports clk_pin]
set_property IOSTANDARD LVCMOS33 [get_ports btn_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rst_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rxd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports txd_pin]
set_property DRIVE 12 [get_ports txd_pin]
set_property SLEW SLOW [get_ports txd_pin]
set_property PACKAGE_PIN H16 [get_ports clk_pin]
set_property PACKAGE_PIN D19 [get_ports btn_pin]
set_property PACKAGE_PIN L19 [get_ports rst_pin]
set_property PACKAGE_PIN Y18 [get_ports rxd_pin]
set_property PACKAGE_PIN Y19 [get_ports txd_pin]
set_property DRIVE 12 [get_ports {led_pins[0]}]
set_property DRIVE 12 [get_ports {led_pins[1]}]
set_property DRIVE 12 [get_ports {led_pins[2]}]
set_property DRIVE 12 [get_ports {led_pins[3]}]
set_property SLEW SLOW [get_ports {led_pins[0]}]
set_property SLEW SLOW [get_ports {led_pins[1]}]
set_property SLEW SLOW [get_ports {led_pins[2]}]
set_property SLEW SLOW [get_ports {led_pins[3]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {led_pins[0]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {led_pins[1]}]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {led_pins[2]}]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {led_pins[3]}]

create_clock -period 8.000 -name clk_pin -waveform {0.000 4.000} [get_ports clk_pin]
