# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.cache/wt} [current_project]
set_property parent.project_path {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-10:part0:1.1 [current_project]
set_property ip_output_repo {e:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/sources_1/imports/Lab02/led_ctl.vhd}
  {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/sources_1/imports/Lab02/meta_harden.vhd}
  {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/sources_1/imports/Lab02/uart_baud_gen.vhd}
  {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/sources_1/imports/Lab02/uart_led.vhd}
  {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/sources_1/imports/Lab02/uart_rx.vhd}
  {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/sources_1/imports/Lab02/uart_rx_ctl.vhd}
  {E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/sources_1/imports/Lab02/uart_top.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/constrs_1/imports/Lab02/uart_led_timing_ArtyZ7.xdc}}
set_property used_in_implementation false [get_files {{E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/constrs_1/imports/Lab02/uart_led_timing_ArtyZ7.xdc}}]

read_xdc {{E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/constrs_1/imports/Lab02/uart_led_pins_ArtyZ7.xdc}}
set_property used_in_implementation false [get_files {{E:/Facultad/Sistemas Digitales/Practicas/Practica02/Practica02.srcs/constrs_1/imports/Lab02/uart_led_pins_ArtyZ7.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top uart_top -part xc7z010clg400-1 -flatten_hierarchy full -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uart_top.dcp
create_report "synth_flatten_synth_report_utilization_0" "report_utilization -file uart_top_utilization_synth.rpt -pb uart_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
